-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.main_dish
(
    id_dish serial NOT NULL,
    description character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT main_dish_pkey PRIMARY KEY (id_dish)
);

CREATE TABLE IF NOT EXISTS public.menu
(
    id_menu serial NOT NULL,
    price real,
    drink character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT menu_pkey PRIMARY KEY (id_menu)
);

CREATE TABLE IF NOT EXISTS public.menu_main_dish
(
    id_dish integer NOT NULL,
    id_menu integer NOT NULL,
    CONSTRAINT menu_main_dish_pkey PRIMARY KEY (id_dish, id_menu)
);

CREATE TABLE IF NOT EXISTS public.side_dish
(
    id_side_dish serial NOT NULL,
    description character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT side_dish_pkey PRIMARY KEY (id_side_dish)
);

CREATE TABLE IF NOT EXISTS public.side_dish_main_dish
(
    id_dish integer NOT NULL,
    id_side_dish integer NOT NULL,
    CONSTRAINT side_dish_main_dish_pkey PRIMARY KEY (id_dish, id_side_dish)
);

ALTER TABLE IF EXISTS public.menu_main_dish
    ADD CONSTRAINT fkeq12qrxgbgty7mt0skia6m69b FOREIGN KEY (id_dish)
    REFERENCES public.main_dish (id_dish) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.menu_main_dish
    ADD CONSTRAINT fkkeoob0yn7e08iw2uvqiwtjo0w FOREIGN KEY (id_menu)
    REFERENCES public.menu (id_menu) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.side_dish_main_dish
    ADD CONSTRAINT fk5rfptnucfbdkoynv4dn95d4f2 FOREIGN KEY (id_dish)
    REFERENCES public.main_dish (id_dish) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.side_dish_main_dish
    ADD CONSTRAINT fke3hw6v62hv9q6lf9ygfergbs0 FOREIGN KEY (id_side_dish)
    REFERENCES public.side_dish (id_side_dish) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;